### ISSUE TITLE
[iOS] Not shown the SpeachSession message if favorited

### ISSUE THREAD

**Issue by nukka123** [DroidKaigi/conference-app-2020#782] opened 2020-02-15 03:07 UTC
**Overview (Required)**
- Not shown the SpeachSession message if favorited.

**Steps To Reproduce**

1. Go to Sessions.
2. Choose the Session with the some message, and Click favorite(bookmark) button.

**Expected behavior**
Keep shown the message.

**Screenshots**

Favorite Off | Favorite On
:--: | :--:
<img src="https://user-images.githubusercontent.com/29206446/74580787-31d25c00-4feb-11ea-9adb-e2752b339232.png" width="300" /> | <img src="https://user-images.githubusercontent.com/29206446/74580783-2da63e80-4feb-11ea-86ca-f8f4a890e5d2.png" width="300" />

**Env:**
 - Device: Simulator iPhone11 Max
 - OS: iOS13
 - master 51f88e9efd5d2d95d0f31b6c5bff03e938aa41ea

**Comment by ry-itto** [comment] 2020-02-15 03:28
This may be caused by `SessionEntity` doesn't have a property `sessionMessage`.
And `RealmToModelMapper` doesn't convert the property.

```swift
return SpeechSession(
                id: SessionId(id: session.id),
                dayNumber: Int32(dayNumber),
                startTime: TimeInterval(session.stime),
                endTime: TimeInterval(session.etime),
                title: LocaledString(ja: session.title, en: session.enTitle),
                desc: session.desc,
                room: Room(
                    id: Int32(room.id),
                    name: LocaledString(ja: room.name, en: room.enName),
                    sort: Int32(room.sort)
                ),
                levels: [],
                lang: session.language == "ja" ? .ja : .en,
                category: Category(
                    id: Int32(category?.id ?? 0),
                    name: LocaledString(
                        ja: category?.name ?? "",
                        en: category?.enName ?? ""
                    )
                ),
                intendedAudience: session.intendedAudience,
                videoUrl: session.videoUrl,
                slideUrl: session.slideUrl,
                isInterpretationTarget: session.isInterpretationTarget,
                isFavorited: session.isFavorited,
                speakers: session.speakers.map { toModel(speakerEntity: $0) },
                message: nil // <- This bug may be fixed by setting message.
            )
```

**Comment by clockvoid** [comment] 2020-02-15 19:04
I want to try this ✋

**Comment by ry-itto** [comment] 2020-02-15 19:25
Thanks!! Assigned 👍 
And thank you for resolving quickly!!

**Closed** 2020-02-15 19:37 UTC
Labels: bug, welcome contribute
