### ISSUE TITLE
input method keyboard from SearchView remains after search operation

### ISSUE THREAD

**Issue by atsushieno** [DroidKaigi/conference-app-2020#285] opened 2020-01-15 17:56 UTC
**Overview (Required)**
- input method keyboard from SearchView on the session list fragment remains after search operation (back, select a people, or select a session)

**Steps To Reproduce**

1. launch the app
2. tap top-right search button. The keyboard widget (depending on the local input method settings) would show up.
3. Try either of these:
  1. tap top-left "back" left arrow.
  2. select a speaker from the list.
  3. scroll down a lot or apply some query filter and then select a session from the list.
4. Confirm that the input method keyboard remains on the screen. It's in the way.

**Expected behavior**

The keyboard would vanish.

**Screenshots**

![image](https://user-images.githubusercontent.com/53929/72457836-cab66180-380a-11ea-8f54-96630827749a.png)

**Env:**
 - Device:Pixel 2
 - OS: Android 10.0 (Build number QQ1A.200105.002)
 - App Version or the branch: build # 60 via DeployGate

**Additional context**

It is likely due to missing SearchView.OnCloseListener to...maybe compact the box? ... or whatever expected. Other Android apps (e.g. "DeployGate" app) usually hides the keyboard so it is not likely an issue in SearchView itself.

**Comment by takahirom** [comment] 2020-01-15 18:26
Thank you for reporting 🙏 
Unfortunately, this issue is duplicate of this issue and the issue is assigned 😭
#133

**Closed** 2020-01-15 18:26 UTC
Labels: bug
