### ISSUE TITLE
Keyboard keep display after page transition

### ISSUE THREAD

**Issue by KeigoNishira** [DroidKaigi/conference-app-2020#279] opened 2020-01-15 16:24 UTC
**Overview (Required)**
- When transition to SearchView, soft keyboard is appear.
   In addition, if user tap Speaker's name, app transition to detailed page, but soft keyboard is still show.
   if user back to main page, soft keyboard is keep show. 
   
**Steps To Reproduce**
1. Go to 'Search'
2. Click on 'Query View'
3. back to main page by cursor button on top of left button.
4. repeat 1 to 2. 
5. tap speaker's name.

**Expected behavior**
On step2, soft keyboard is disappear.
On step3. soft keyboard is disappear.
On step5, soft keyboard is disappear.

**Screenshots**
![keyboard_display_when_transition_to_searchView](https://user-images.githubusercontent.com/47495080/72451029-a94f7880-37fe-11ea-95f1-f86aadc4dc17.png)
![keyboard_not_disappear_when_transition_to_detail_page](https://user-images.githubusercontent.com/47495080/72451033-ace2ff80-37fe-11ea-835a-8aff5d1f872a.png)

**Env:**
 - Device: Xperia XZ3
 - OS: 9.0
 - App Version or the branch master

**Additional context**
Ready to fix on locally.

**Comment by takahirom** [comment] 2020-01-15 16:27
Thanks 👍 
Unfortunately, this issue is duplicate of this issue and the issue is assigned 😭 
https://github.com/DroidKaigi/conference-app-2020/issues/133

**Closed** 2020-01-15 16:27 UTC
Labels: bug

**Comment by KeigoNishira** [comment] 2020-01-15 16:36
OK, I'm sorry for bothering you.
